import { Navigation } from "@/components/layout/navigation";
import { Footer } from "@/components/layout/footer";
import "../styles/index.css";
import "../styles/media.css"
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Navigation />

        <div className="site-container">{children}</div>

        <Footer />
      </body>
    </html>
  );
}
